"""Build the EasyGo LVGL font subset and simulated SD-card map.

The script is intentionally self-contained and uses only Pillow plus the raw
OpenStreetMap JSON snapshot committed under Simulator/SD/MAP.
"""

from __future__ import annotations

import json
import math
import struct
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


REPO = Path(__file__).resolve().parents[3]
FONT_DIR = REPO / "3.Firmware/PlatformIO/EasyGo-ESP32-fw/src/App/Resources/Font"
MAP_DIR = REPO / "4.Software/Simulator/SD/MAP"
FONT_REGULAR = Path(r"C:\Windows\Fonts\msyh.ttc")
FONT_BOLD = Path(r"C:\Windows\Fonts\msyhbd.ttc")
BAOAN_RELATION_ID = 5664101
MAP_SOURCE_NAME = "shenzhen_baoan.osm.json"
MAP_IMAGE_NAME = "shenzhen.bin"
TOILET_INDEX_NAME = "shenzhen_toilets.bin"
MAP_LEVEL_INDEX_NAME = "shenzhen_levels.bin"
MAP_FOCUS_LAT = 22.5533410
MAP_FOCUS_LON = 113.8782710
MAP_ZOOM_FACTORS = (1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0)
MAP_VIEWPORT_SIZE = (240, 164)
MAP_CANVAS_SCALE = 3
MAP_CANVAS_SIZE = (
    MAP_VIEWPORT_SIZE[0] * MAP_CANVAS_SCALE,
    MAP_VIEWPORT_SIZE[1] * MAP_CANVAS_SCALE,
)
MAP_CANVAS_INSET = 8 * MAP_CANVAS_SCALE
MAP_INITIAL_SCROLL = (
    (MAP_CANVAS_SIZE[0] - MAP_VIEWPORT_SIZE[0]) // 2,
    (MAP_CANVAS_SIZE[1] - MAP_VIEWPORT_SIZE[1]) // 2,
)

UI_TEXT = """
安心出行方便随行寻厕宝寻厕引路找厕所导航亲情守护紧急联系人设置常用
直行米前方公共厕所距离约分钟女儿子老伴一键求助发送位置给联系人
正在启动个性使用语音播报开启后将提示语言选择当前简体中文屏幕亮度
电子围栏未设置紧急提醒关于我们返回首页模拟呼叫演示求助未发送未拨号·♥
孙女弟弟邻居社区服务物业亲友备用联系人上下滑动查看更多
深圳市民中心深南大道金田路益田路福中路厕所地图资源加载失败
"""
CHARS = "".join(chr(code) for code in range(0x20, 0x7F)) + UI_TEXT


def _hex_rows(data: bytes, width: int = 16) -> str:
    rows = []
    for start in range(0, len(data), width):
        chunk = data[start : start + width]
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


def _number_rows(values: list[int], width: int = 12) -> str:
    rows = []
    for start in range(0, len(values), width):
        chunk = values[start : start + width]
        rows.append("    " + ", ".join(str(value) for value in chunk) + ",")
    return "\n".join(rows)


def build_font(size: int, bold: bool = False) -> None:
    font_path = FONT_BOLD if bold else FONT_REGULAR
    pil_font = ImageFont.truetype(str(font_path), size=size)
    codepoints = sorted(set(ord(char) for char in CHARS if char not in "\r\n"))
    ascii_codepoints = [codepoint for codepoint in codepoints if 0x20 <= codepoint <= 0x7E]
    extra_codepoints = [codepoint for codepoint in codepoints if codepoint > 0x7E]

    bitmap = bytearray()
    descriptors: list[tuple[int, int, int, int, int, int]] = [(0, 0, 0, 0, 0, 0)]
    unicode_list: list[int] = []
    range_start = extra_codepoints[0]

    for codepoint in codepoints:
        char = chr(codepoint)
        left, top, right, bottom = pil_font.getbbox(char, anchor="ls")
        box_w = max(0, right - left)
        box_h = max(0, bottom - top)
        bitmap_index = len(bitmap)

        if box_w and box_h:
            mask = Image.new("L", (box_w, box_h), 0)
            draw = ImageDraw.Draw(mask)
            draw.text((-left, -top), char, fill=255, font=pil_font, anchor="ls")
            pixels = list(mask.getdata())
            for index in range(0, len(pixels), 2):
                high = (pixels[index] + 8) // 17
                low = (pixels[index + 1] + 8) // 17 if index + 1 < len(pixels) else 0
                bitmap.append((min(high, 15) << 4) | min(low, 15))

        advance = int(round(pil_font.getlength(char) * 16))
        descriptors.append((bitmap_index, advance, box_w, box_h, left, -bottom))
        if codepoint > 0x7E:
            unicode_list.append(codepoint - range_start)

    ascent, descent = pil_font.getmetrics()
    line_height = ascent + descent
    name = f"font_easygo_{size}"
    glyph_rows = "\n".join(
        "    { .bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d },"
        % item
        for item in descriptors
    )

    source = f"""/*
 * Generated by 4.Software/UI/tools/build_lvgl_assets.py.
 * Font: Microsoft YaHei ({'bold' if bold else 'regular'}), {size}px, 4bpp.
 * Contains only glyphs used by the EasyGo simulator UI.
 */
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{_hex_rows(bytes(bitmap))}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{glyph_rows}
}};

static const uint16_t unicode_list[] = {{
{_number_rows(unicode_list)}
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 32,
        .range_length = 95,
        .glyph_id_start = 1,
        .unicode_list = NULL,
        .glyph_id_ofs_list = NULL,
        .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }},
    {{
        .range_start = {range_start},
        .range_length = {extra_codepoints[-1] - range_start + 1},
        .glyph_id_start = {len(ascii_codepoints) + 1},
        .unicode_list = unicode_list,
        .glyph_id_ofs_list = NULL,
        .list_length = {len(extra_codepoints)},
        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }}
}};

#if LV_VERSION_CHECK(8, 0, 0)
static lv_font_fmt_txt_glyph_cache_t cache;
#endif

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
}};

const lv_font_t {name} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {line_height},
    .base_line = {descent},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = &font_dsc
}};
"""
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    (FONT_DIR / f"{name}.c").write_text(source, encoding="utf-8", newline="\n")


def _project(
    lat: float,
    lon: float,
    bounds: tuple[float, float, float, float],
    size: tuple[int, int],
) -> tuple[int, int]:
    south, west, north, east = bounds
    width, height = size
    x = MAP_CANVAS_INSET + (lon - west) / (east - west) * (
        width - MAP_CANVAS_INSET * 2
    )
    y = MAP_CANVAS_INSET + (north - lat) / (north - south) * (
        height - MAP_CANVAS_INSET * 2
    )
    return round(x), round(y)


def _baoan_bounds(data: dict) -> tuple[float, float, float, float]:
    for element in data["elements"]:
        if element.get("type") == "relation" and element.get("id") == BAOAN_RELATION_ID:
            bounds = element.get("bounds")
            if bounds:
                return bounds["minlat"], bounds["minlon"], bounds["maxlat"], bounds["maxlon"]
    raise ValueError(f"Bao'an relation {BAOAN_RELATION_ID} has no bounds")


def _toilet_position(element: dict) -> tuple[float, float] | None:
    if element.get("type") == "node" and "lat" in element and "lon" in element:
        return element["lat"], element["lon"]
    center = element.get("center")
    if center and "lat" in center and "lon" in center:
        return center["lat"], center["lon"]
    geometry = [point for point in element.get("geometry", []) if "lat" in point and "lon" in point]
    if geometry:
        return (
            sum(point["lat"] for point in geometry) / len(geometry),
            sum(point["lon"] for point in geometry) / len(geometry),
        )
    return None


def _fixed_utf8(value: str, limit: int) -> bytes:
    encoded = value.encode("utf-8")
    while len(encoded) > limit:
        value = value[:-1]
        encoded = value.encode("utf-8")
    return encoded


def _toilet_flags(tags: dict) -> int:
    flags = 0
    flags |= 1 << 0 if tags.get("wheelchair") == "yes" else 0
    flags |= 1 << 1 if tags.get("wheelchair") == "limited" else 0
    flags |= 1 << 2 if tags.get("wheelchair") == "no" else 0
    flags |= 1 << 3 if tags.get("fee") == "yes" else 0
    flags |= 1 << 4 if tags.get("fee") == "no" else 0
    flags |= 1 << 5 if tags.get("unisex") == "yes" else 0
    flags |= 1 << 6 if tags.get("opening_hours") else 0
    flags |= 1 << 7 if tags.get("access") not in (None, "yes", "public", "permissive") else 0
    return flags


def build_toilet_index(data: dict, bounds: tuple[float, float, float, float]) -> int:
    records = bytearray()
    type_ids = {"node": 0, "way": 1, "relation": 2}
    toilets = [
        element
        for element in data["elements"]
        if element.get("tags", {}).get("amenity") == "toilets" and _toilet_position(element)
    ]
    toilets.sort(key=lambda element: (type_ids.get(element.get("type"), 255), element["id"]))

    for element in toilets:
        lat, lon = _toilet_position(element)
        tags = element.get("tags", {})
        name = _fixed_utf8(tags.get("name", ""), 44)
        records.extend(
            struct.pack(
                "<QiiHBB44s",
                element["id"],
                round(lat * 10_000_000),
                round(lon * 10_000_000),
                _toilet_flags(tags),
                type_ids[element["type"]],
                len(name),
                name.ljust(44, b"\0"),
            )
        )

    timestamp = data.get("osm3s", {}).get("timestamp_osm_base", "")
    data_date = int(timestamp[:10].replace("-", "")) if len(timestamp) >= 10 else 0
    south, west, north, east = bounds
    header = struct.pack(
        "<8sHHIIIIiiiiI",
        b"EGTOIL1\0",
        1,
        48,
        len(toilets),
        64,
        10_000_000,
        data_date,
        round(south * 10_000_000),
        round(west * 10_000_000),
        round(north * 10_000_000),
        round(east * 10_000_000),
        zlib.crc32(records),
    )
    (MAP_DIR / TOILET_INDEX_NAME).write_bytes(header + records)
    return len(toilets)


def _zoomed_bounds(
    bounds: tuple[float, float, float, float],
    zoom_factor: float,
    focus: tuple[float, float],
) -> tuple[float, float, float, float]:
    south, west, north, east = bounds
    half_lat = (north - south) / (2 * zoom_factor)
    half_lon = (east - west) / (2 * zoom_factor)
    return focus[0] - half_lat, focus[1] - half_lon, focus[0] + half_lat, focus[1] + half_lon


def _expanded_bounds(
    bounds: tuple[float, float, float, float],
    factor: float,
) -> tuple[float, float, float, float]:
    south, west, north, east = bounds
    center_lat = (south + north) / 2
    center_lon = (west + east) / 2
    half_lat = (north - south) * factor / 2
    half_lon = (east - west) * factor / 2
    return (
        center_lat - half_lat,
        center_lon - half_lon,
        center_lat + half_lat,
        center_lon + half_lon,
    )


def _render_map(
    data: dict, bounds: tuple[float, float, float, float], size: tuple[int, int]
) -> Image.Image:
    image = Image.new("RGB", size, "#eaf1ed")
    draw = ImageDraw.Draw(image)
    label_font = ImageFont.truetype(str(FONT_REGULAR), 9)
    tiny_font = ImageFont.truetype(str(FONT_REGULAR), 8)

    # Draw lower-class roads first so the district remains readable at 240 px.
    road_order = {"tertiary": 0, "secondary": 1, "primary": 2, "trunk": 3, "motorway": 4}
    roads = []
    for element in data["elements"]:
        tags = element.get("tags", {})
        if element.get("type") != "way" or "geometry" not in element or "highway" not in tags:
            continue
        road_class = tags["highway"].replace("_link", "")
        roads.append((road_order.get(road_class, 0), road_class, element))

    for _, road_class, element in sorted(roads, key=lambda item: item[0]):
        points = [_project(p["lat"], p["lon"], bounds, size) for p in element["geometry"]]
        if len(points) < 2:
            continue
        width = {"motorway": 4, "trunk": 3, "primary": 3, "secondary": 2, "tertiary": 1}.get(road_class, 1)
        color = {"motorway": "#f3a95f", "trunk": "#f6c075", "primary": "#ffffff"}.get(road_class, "#ffffff")
        if width >= 2:
            draw.line(points, fill="#cfd7d2", width=width + 2, joint="curve")
        draw.line(points, fill=color, width=width, joint="curve")

    seen_labels: set[str] = set()
    occupied: list[tuple[int, int]] = []
    for _, road_class, element in sorted(roads, key=lambda item: item[0], reverse=True):
        name = element.get("tags", {}).get("name")
        if not name or name in seen_labels or road_class not in {"motorway", "trunk", "primary"}:
            continue
        geometry = element["geometry"]
        midpoint = geometry[len(geometry) // 2]
        x, y = _project(midpoint["lat"], midpoint["lon"], bounds, size)
        if x < -20 or x > size[0] + 20 or y < -12 or y > size[1] + 12:
            continue
        if any(abs(x - old_x) < 34 and abs(y - old_y) < 14 for old_x, old_y in occupied):
            continue
        seen_labels.add(name)
        occupied.append((x, y))
        draw.text((x + 2, y + 2), name[:8], font=label_font, fill="#7e8582")

    for element in data["elements"]:
        if element.get("tags", {}).get("amenity") != "toilets":
            continue
        position = _toilet_position(element)
        if not position:
            continue
        x, y = _project(*position, bounds, size)
        draw.ellipse((x - 2, y - 2, x + 2, y + 2), fill="#2f80ed", outline="#ffffff")

    draw.rounded_rectangle((8, 8, 56, 25), radius=6, fill="#ffffff", outline="#d8dfda")
    draw.text((15, 11), "宝安区", font=label_font, fill="#203247")

    attribution = "© OpenStreetMap contributors"
    box = draw.textbbox((0, 0), attribution, font=tiny_font)
    draw.rectangle((size[0] - (box[2] - box[0]) - 4, size[1] - 12, size[0], size[1]), fill="#ffffff")
    draw.text((size[0] - (box[2] - box[0]) - 2, size[1] - 11), attribution, font=tiny_font, fill="#5f6663")
    return image


def _write_lvgl_image(image: Image.Image, path: Path) -> None:
    size = image.size
    header = 4 | (size[0] << 10) | (size[1] << 21)  # LV_IMG_CF_TRUE_COLOR
    pixels = bytearray()
    for red, green, blue in image.getdata():
        rgb565 = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        pixels.extend(struct.pack("<H", rgb565))
    path.write_bytes(struct.pack("<I", header) + pixels)


def _build_map_level_index(
    data: dict,
    levels: list[tuple[int, float, tuple[float, float, float, float]]],
    size: tuple[int, int],
) -> None:
    coordinate_scale = 10_000_000
    inset_x = MAP_CANVAS_INSET
    inset_y = MAP_CANVAS_INSET
    records = bytearray()

    for level, zoom_factor, bounds in levels:
        south, west, north, east = bounds
        center_lat = (south + north) / 2
        meters_per_degree_lat = 111_320.0
        meters_per_degree_lon = 111_320.0 * math.cos(math.radians(center_lat))
        meters_per_pixel_x = (east - west) * meters_per_degree_lon / (size[0] - inset_x * 2)
        meters_per_pixel_y = (north - south) * meters_per_degree_lat / (size[1] - inset_y * 2)
        records.extend(
            struct.pack(
                "<B3xIiiiiII",
                level,
                round(zoom_factor * 1000),
                round(south * coordinate_scale),
                round(west * coordinate_scale),
                round(north * coordinate_scale),
                round(east * coordinate_scale),
                round(meters_per_pixel_x * 1000),
                round(meters_per_pixel_y * 1000),
            )
        )

    timestamp = data.get("osm3s", {}).get("timestamp_osm_base", "")
    data_date = int(timestamp[:10].replace("-", "")) if len(timestamp) >= 10 else 0
    header = struct.pack(
        "<8sHHIIIiiHHHHHHiiIII",
        b"EGMAPL2\0",
        2,
        64,
        len(levels),
        32,
        coordinate_scale,
        round(MAP_FOCUS_LAT * coordinate_scale),
        round(MAP_FOCUS_LON * coordinate_scale),
        size[0],
        size[1],
        MAP_VIEWPORT_SIZE[0],
        MAP_VIEWPORT_SIZE[1],
        inset_x,
        inset_y,
        MAP_INITIAL_SCROLL[0],
        MAP_INITIAL_SCROLL[1],
        zlib.crc32(records),
        data_date,
        0,
    )
    (MAP_DIR / MAP_LEVEL_INDEX_NAME).write_bytes(header + records)


def build_map() -> None:
    source_path = MAP_DIR / MAP_SOURCE_NAME
    data = json.loads(source_path.read_text(encoding="utf-8"))
    bounds = _baoan_bounds(data)
    size = MAP_CANVAS_SIZE
    zoom_levels = (
        (MAP_ZOOM_FACTORS[0], "shenzhen_z0.bin"),
        (MAP_ZOOM_FACTORS[1], "shenzhen_z1.bin"),
        (MAP_ZOOM_FACTORS[2], "shenzhen_z2.bin"),
        (MAP_ZOOM_FACTORS[3], MAP_IMAGE_NAME),
        (MAP_ZOOM_FACTORS[4], "shenzhen_z4.bin"),
        (MAP_ZOOM_FACTORS[5], "shenzhen_z5.bin"),
        (MAP_ZOOM_FACTORS[6], "shenzhen_z6.bin"),
    )

    generated_levels = []
    for level, (zoom_factor, filename) in enumerate(zoom_levels):
        viewport_bounds = bounds if level == 0 else _zoomed_bounds(
            bounds, zoom_factor, (MAP_FOCUS_LAT, MAP_FOCUS_LON)
        )
        level_bounds = _expanded_bounds(viewport_bounds, MAP_CANVAS_SCALE)
        generated_levels.append((level, zoom_factor, level_bounds))
        image = _render_map(data, level_bounds, size)
        _write_lvgl_image(image, MAP_DIR / filename)
        if level == 3:
            _write_lvgl_image(image, MAP_DIR / "shenzhen_z3.bin")
            image.save(MAP_DIR / "shenzhen_map.png")

    _build_map_level_index(data, generated_levels, size)
    toilet_count = build_toilet_index(data, bounds)

    attribution_path = MAP_DIR / "ATTRIBUTION.md"
    attribution_path.write_text(
        f"""# Shenzhen Bao'an simulator map data

- Source: © OpenStreetMap contributors, queried through the Overpass API.
- Query: `shenzhen_baoan.overpassql`
- Snapshot: `shenzhen_baoan.osm.json`
- OSM administrative relation: `{BAOAN_RELATION_ID}` (Bao'an District).
- WGS84 bounds: south {bounds[0]:.7f}, west {bounds[1]:.7f}, north {bounds[2]:.7f}, east {bounds[3]:.7f}.
- OSM snapshot timestamp: {data.get("osm3s", {}).get("timestamp_osm_base", "unknown")}.
- Included features: major roads and {toilet_count} objects tagged `amenity=toilets`.
- Raster levels: 1x, 2x, 4x, 8x, 16x, 32x and 64x.
- Every raster is a {MAP_CANVAS_SIZE[0]}x{MAP_CANVAS_SIZE[1]} pan canvas for a
  {MAP_VIEWPORT_SIZE[0]}x{MAP_VIEWPORT_SIZE[1]} viewport.
- Simulator focus (WGS84): {MAP_FOCUS_LAT:.7f}, {MAP_FOCUS_LON:.7f}.
- Level georeferencing index: `shenzhen_levels.bin`.
- License: Open Data Commons Open Database License (ODbL).
- Required attribution: © OpenStreetMap contributors; https://www.openstreetmap.org/copyright
- Purpose: offline simulator demonstration only. It is not a validated
  routing, accessibility, emergency-response, or production navigation dataset.
""",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    build_font(12)
    build_font(14)
    build_font(16)
    build_font(20)
    build_font(28, bold=True)
    build_map()
    print("Generated EasyGo font subsets and Shenzhen Bao'an SD-card map/POI assets.")
